name: login_funcional
description: "App de revisión periódica de furgonetas VRP Electric"
publish_to: none

version: 1.0.6+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  
  # PDF generation
  pdf: ^3.10.7
  
  # Email sending
  mailer: ^6.0.1
  
  # Image handling
  image_picker: ^1.0.7
  image: ^4.1.7
  
  # ✅ PERMISOS AÑADIDO
  permission_handler: ^11.3.1
  
  # Date formatting
  intl: ^0.19.0
  
  # File operations
  path_provider: ^2.1.2
  


  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  shared_preferences: ^2.5.3
  # Your other existing dependencies...
  # material_design_icons_flutter: ^7.0.7296
  # etc...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/assets/icons/

# Configuración del generador de iconos
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/furgorevicon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#0082C2"
  adaptive_icon_foreground: "lib/assets/icons/furgorevicon.png"
  web:
    generate: true
    image_path: "lib/assets/icons/furgorevicon.png"
    background_color: "#0082C2"
    theme_color: "#4DA7D4"
  windows:
    generate: true
    image_path: "lib/assets/icons/furgorevicon.png"
    icon_size: 48